export enum AppRoutes {
  Home = '/',
  Login = '/login',
  Register = '/register',
  ForgotPassword = '/forgot-password',
  ResetPassword = '/reset-password',
  EmailConfirmation = '/email-confirmation',
  Cart = '/cart',
  Wishlist = '/wishlist',
  Checkout = '/checkout',
  OrderSuccess = '/order-success',
  Rewards = '/rewards',
  AccountDashboard = '/my-account/dashboard',
  AccountOrders = '/my-account/orders',
  AccountLoyalty = '/my-account/loyalty',
  AccountAddress = '/my-account/address',
  AccountDetails = '/my-account/account-details',
  Collection = '/collection',
  CollectionMen = '/collection/men',
  CollectionWomen = '/collection/women',
  AboutUs = '/about-us',
  PrivacyPolicy = '/privacy-policy',
  TermsAndConditions = '/terms-and-conditions',
  ReturnPolicy = '/return-policy',
  ShippingPolicy = '/shipping-policy',
  SizeGuide = '/size-guide',
  Faq = '/faq',
  SampleProduct = '/products/berserk-oversized-tee',
}

export enum UserRoles {
  Guest = 'guest',
  Customer = 'customer',
}
